<a href="https://colab.research.google.com/github/granantuin/Model_vs_data_label/blob/master/Copia_de_Display_x_y_data_rawmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas_ml

    100% |████████████████████████████████| 102kB 2.7MB/s 


In [0]:
from sklearn.metrics import confusion_matrix ,accuracy_score,f1_score,recall_score
from sklearn.metrics import precision_recall_fscore_support
from pandas_ml import ConfusionMatrix
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


In [3]:
from google.colab import drive
drive.mount('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
y_data=pd.read_excel("/content/drive/My Drive/Colab Notebooks/model_vs_data/Coron_Mars_H24to48_dir/y_data.xlsx")
x_data=pd.read_csv("/content/drive/My Drive/Colab Notebooks/model_vs_data/Coron_Mars_H24to48_dir/x_data",usecols=range(1,10))

In [6]:
NE=y_data[(y_data["value"]>22.5) & (y_data["value"]<67.5)]
NE["label"]="NE"
E=y_data[(y_data["value"]>67.5) & (y_data["value"]<112.5)]
E["label"]="E"
SE=y_data[(y_data["value"]>112.5) & (y_data["value"]<157.5)]
SE["label"]="SE"
S=y_data[(y_data["value"]>157.5) & (y_data["value"]<202.5)]
S["label"]="S"
SW=y_data[(y_data["value"]>202.5) & (y_data["value"]<247.5)]
SW["label"]="SW"
W=y_data[(y_data["value"]>247.5) & (y_data["value"]<292.5)]
W["label"]="W"
NW=y_data[(y_data["value"]>292.5) & (y_data["value"]<337.5)]
NW["label"]="NW"
N=y_data[(y_data["value"]>337.5) | (y_data["value"]<22.5)]
N["label"]="N"
winds=[NE,N,E,SE,S,SW,W,NW]
y_data=pd.concat(winds)
y_data=y_data.sort_values(by="DATA (Horario UTC)")


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs

In [0]:
y_data

In [0]:
x_data["date"]=y_data["DATA (Horario UTC)"]

In [0]:
x_data

In [10]:
for c in ['0', '1', '2', '3', '4', '5', '6', '7', '8']:
  NE=x_data[(x_data[c]>22.5) & (x_data[c]<67.5)]
  NE["label"+c]="NE"
  E=x_data[(x_data[c]>67.5) & (x_data[c]<112.5)]
  E["label"+c]="E"
  SE=x_data[(x_data[c]>112.5) & (x_data[c]<157.5)]
  SE["label"+c]="SE"
  S=x_data[(x_data[c]>157.5) & (x_data[c]<202.5)]
  S["label"+c]="S"
  SW=x_data[(x_data[c]>202.5) & (x_data[c]<247.5)]
  SW["label"+c]="SW"
  W=x_data[(x_data[c]>247.5) & (x_data[c]<292.5)]
  W["label"+c]="W"
  NW=x_data[(x_data[c]>292.5) & (x_data[c]<337.5)]
  NW["label"+c]="NW"
  N=x_data[(x_data[c]>337.5) | (x_data[c]<22.5)]
  N["label"+c]="N"
  winds=[NE,N,E,SE,S,SW,W,NW]
  x_data=pd.concat(winds)
  x_data=x_data.sort_values(by="date")
  
  

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the docume

In [0]:
x_data=x_data.iloc[:, 10:]

In [0]:
x_data

In [47]:
for label in x_data.columns:
  print(label)
  print("accuracy="+"{:.2%}"".format(accuracy_score(y_data["label"], x_data[label]))
  

SyntaxError: ignored

In [0]:
for label in x_data.columns:
  print(label)
  print(ConfusionMatrix(y_data["label"],x_data[label]))
  
  

label0
Predicted   E    N   NE  NW   S  SE  SW   W  __all__
Actual                                              
E           2    3   20   1   8   6   0   1       41
N           1   13   19   1   2   1   1   3       41
NE         14   66  165  23  21   6  21  18      334
NW          0    7    3   0   0   0   2   3       15
S           0    9    8   2   5   0   7   2       33
SE          0    7    8   2   1   2   1   2       23
SW          1   13   16   2   5   0  13   7       57
W           0   11   16   4   2   1  16   6       56
__all__    18  129  255  35  44  16  61  42      600
label1
Predicted   E    N   NE  NW   S  SE  SW   W  __all__
Actual                                              
E           8    5   14   0   8   4   1   1       41
N           2   18   13   0   2   1   3   2       41
NE         28   93  126  22  23   5  19  18      334
NW          0    7    3   0   0   0   2   3       15
S           1   10    7   1   6   0   7   1       33
SE          1    7    8   1   1 

In [0]:
results= precision_recall_fscore_support(y_data["label"], x_data["label8"], average=None, )

In [20]:
results

(array([0.11904762, 0.11794872, 0.61146497, 0.03125   , 0.15555556,
        0.0952381 , 0.234375  , 0.18181818]),
 array([0.12195122, 0.56097561, 0.28742515, 0.06666667, 0.21212121,
        0.08695652, 0.26315789, 0.14285714]),
 array([0.12048193, 0.19491525, 0.3910387 , 0.04255319, 0.17948718,
        0.09090909, 0.24793388, 0.16      ]),
 array([ 41,  41, 334,  15,  33,  23,  57,  56]))

In [21]:
results[0]

array([0.11904762, 0.11794872, 0.61146497, 0.03125   , 0.15555556,
       0.0952381 , 0.234375  , 0.18181818])

In [50]:
for label in x_data.columns:
  print(label)
  print("accuracy=","{:.2%}".format(accuracy_score(y_data["label"], x_data[label])))
  index=["E","N","NE","NW","S","SE","SW","W"]
  results= precision_recall_fscore_support(y_data["label"], x_data[label], average=None, )
  df=pd.DataFrame({"Precision":results[0],"Recall":results[1],"F1":results[2],"W_DIR":index})
  df=df.set_index("W_DIR")
  print(df)


label0
accuracy= 34.33%
             F1  Precision    Recall
W_DIR                               
E      0.067797   0.111111  0.048780
N      0.152941   0.100775  0.317073
NE     0.560272   0.647059  0.494012
NW     0.000000   0.000000  0.000000
S      0.129870   0.113636  0.151515
SE     0.102564   0.125000  0.086957
SW     0.220339   0.213115  0.228070
W      0.122449   0.142857  0.107143
label1
accuracy= 30.00%
             F1  Precision    Recall
W_DIR                               
E      0.195122   0.195122  0.195122
N      0.173077   0.107784  0.439024
NE     0.471028   0.626866  0.377246
NW     0.000000   0.000000  0.000000
S      0.148148   0.125000  0.181818
SE     0.111111   0.153846  0.086957
SW     0.222222   0.216667  0.228070
W      0.145833   0.175000  0.125000
label2
accuracy= 32.00%
             F1  Precision    Recall
W_DIR                               
E      0.152381   0.125000  0.195122
N      0.228916   0.152000  0.463415
NE     0.499076   0.652174  0.404192
NW 

In [39]:
df["F1"].mean()

0.1784149030836203

In [40]:
df

F1  Precision    Recall
W_DIR                               
E      0.120482   0.119048  0.121951
N      0.194915   0.117949  0.560976
NE     0.391039   0.611465  0.287425
NW     0.042553   0.031250  0.066667
S      0.179487   0.155556  0.212121
SE     0.090909   0.095238  0.086957
SW     0.247934   0.234375  0.263158
W      0.160000   0.181818  0.142857

In [0]:
confusion_matrix(y_data["label"],x_data["label8"])